// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1B0D1rU2QenicFIfgD0DMr89dnf6FUSw',
    appId: '1:392139443843:web:64966caf20c4d3bb2755b6',
    messagingSenderId: '392139443843',
    projectId: 'sign-taxi',
    authDomain: 'sign-taxi.firebaseapp.com',
    storageBucket: 'sign-taxi.firebasestorage.app',
    measurementId: 'G-KMS4KRCPXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCNN8oO9y7RjEBppQlH6BtsKaBwqBf3XU',
    appId: '1:392139443843:android:d5e37c1f20c761432755b6',
    messagingSenderId: '392139443843',
    projectId: 'sign-taxi',
    storageBucket: 'sign-taxi.firebasestorage.app',
  );
}
